# Generated by Django 5.2.1 on 2025-05-14 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemart', '0008_alter_celular_marca_alter_customuser_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='marca',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Apple', 'Apple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
